#!/usr/bin/env node
/**
 * Compact text corpus for the GitHub Pages chat widget (no MCP server).
 * Skip DREAM titles (bulk) and clip long chunks. Regenerated by
 * `yarn build-chat-index`.
 */

import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { buildTextChunks } from "./chunks.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "docs/assets/chat-index.json");
const SKIP = new Set(["dream_title"]);
const MAX_TEXT = 900;

const CONTEXT = `Партнери для МСС — стейкхолдерський сайт + корпус стратегій.
Product unit = candidate IMC/МСС agreement (pair · theme · one of 5 Law 1508-VII forms).
Discovery signals ≠ legal forms. Matching score is a hypothesis unless known=true / registry_known.
Do not treat twinning, Interreg, Law 3668, complementary, or basin as МСС forms or known:true.
Goals coverage is a sample (~394 / 1463 hromadas) — do not generalise to all Ukraine.
This static chat has search_chunks over strategy fields + site pages; it does not run SQL over matching-edges.
Cite hromada name + field, or docs/*.html path for site copy. Never invent quotes.`;

function compact() {
  const rows = buildTextChunks(ROOT)
    .filter((c) => !SKIP.has(c.field))
    .map((c) => {
      const t = c.text.length > MAX_TEXT ? `${c.text.slice(0, MAX_TEXT - 1)}…` : c.text;
      const row: Record<string, string> = { n: c.short || c.name, f: c.field, t };
      if (c.katottg) row.k = c.katottg;
      if (c.oblast) row.o = c.oblast;
      if (c.source) row.s = c.source;
      return row;
    });
  return {
    v: 1,
    generatedAt: new Date().toISOString(),
    n: rows.length,
    context: CONTEXT,
    chunks: rows,
  };
}

const payload = compact();
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(payload));
console.log(`Wrote ${OUT} — ${payload.n} chunks, ${(JSON.stringify(payload).length / 1e6).toFixed(2)} MB`);
